#!/bin/sh
set -e

echo "=== PREPARING CACHE FOLDERS ==="
mkdir -p $APP_PATH/vendor/bundle $APP_PATH/node_modules $APP_PATH/public

echo "=== PREPARING HOME FOLDER ==="
sudo chown dfsobreira:dfsobreira $HOME

echo "=== INSTALLING DEPENDENCIES ==="
bundle install
yarn install

echo "=== CLEANING OLD DEPENDENCIES, ASSETS AND LOGS ==="
bundle clean
rails assets:clean log:clear tmp:clear

if [ ! -f "$HOME/.setup_complete" ]; then
  echo "=== SETTING UP PROJECT ==="
  #chsh -s /bin/zsh

  echo "=== INSTALLING OHMYZSH ==="
  if [ "$BUILDPLATFORM" != "linux/arm64" ] && [ ! -d "$HOME/.oh-my-zsh" ]; then sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -) --unattended"; fi

  echo "=== SETTING UP DATABASE ==="
  rails db:create  db:migrate

  if [ "$NO_SEEDS" != "true" ]; then
    echo "=== SEEDING DATABASE ==="
    rails db:seed
  fi

  # To generate initial assets
  yarn build

  touch "$HOME/.setup_complete"
fi

echo "=== APPLYING LATEST MIGRATIONS ==="
rails db:migrate

echo "=== STARTING WEB SERVER AND CSS AND JS BUILD ==="
./bin/dev
